version: '3'

services:
  hoshikumo-bot:
    build: .
    restart: always
    image: hoshikumo-bot
    container_name: 'hoshikumo-bot'
    ports:
      - '1551:1551'
    volumes:
      - db:/src/db
      - log:/src/log
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: 'hoshikumo-redis'
    restart: always
    volumes:
        - redis-data:/data

volumes:
  db:
  log:
  redis-data:
