version: '3'

services:
  hoshikumo-bot:
    build: .
    image: hoshikumo-bot
    container_name: 'hoshikumo-bot'
    ports:
      - '1551:1551'
    volumes:
      - db:/src/db
      - logs:/src/logs
volumes:
  db:
  logs:
